In [2]:
import numpy as np
import matplotlib.pyplot as plt

In [79]:
x1 = np.matrix([1, -1, 1, -1, 1, -1])
x2 = np.matrix([1, 1, 1, -1, -1, -1])

y1 = np.matrix([1, -1, 1, -1])
y2 = np.matrix([1, 1, -1, -1])

In [80]:
A = x1.transpose() @ y1 + x2.transpose() @ y2
A

matrix([[ 2,  0,  0, -2],
        [ 0,  2, -2,  0],
        [ 2,  0,  0, -2],
        [-2,  0,  0,  2],
        [ 0, -2,  2,  0],
        [-2,  0,  0,  2]])

In [81]:
def normalize(v):
    v[v < 0] = -1
    v[v > 0] = 1
    v[v == 0] = np.random.choice([1, -1], size=1)
    return v

In [82]:
X = np.stack([x1, x2])
Y = np.stack([y1, y2])

X, Y

(matrix([[ 1, -1,  1, -1,  1, -1],
         [ 1,  1,  1, -1, -1, -1]]), matrix([[ 1, -1,  1, -1],
         [ 1,  1, -1, -1]]))

In [83]:
A = X.transpose() @ Y
A

matrix([[ 2,  0,  0, -2],
        [ 0,  2, -2,  0],
        [ 2,  0,  0, -2],
        [-2,  0,  0,  2],
        [ 0, -2,  2,  0],
        [-2,  0,  0,  2]])

In [112]:
p1 = np.copy(X[0])
p1[0,0] = -p1[0,0]

print(X[0], p1)
print(normalize(p1 @ A), Y[0])
print(p1 @ A @ Y[0].transpose())

[[ 1 -1  1 -1  1 -1]] [[-1 -1  1 -1  1 -1]]
[[ 1 -1  1 -1]] [[ 1 -1  1 -1]]
[[16]]


In [119]:
s1 = normalize(p1 @ A)
print(s1)
print("Entropy: ", p1 @ A @ s1.transpose())
p2 = normalize(s1 @ A.transpose())
print(p2)
s2 = normalize(p2 @ A)
print(s2)
print("Entropy: ", p2 @ A @ s2.transpose())
p3 = normalize(s2 @ A.transpose())
print(p3)
s3 = normalize(p3 @ A)
print(s3)
print("Entropy: ", p3 @ A @ s3.transpose())

[[ 1 -1  1 -1]]
Entropy:  [[16]]
[[ 1 -1  1 -1  1 -1]]
[[ 1 -1  1 -1]]
Entropy:  [[24]]
[[ 1 -1  1 -1  1 -1]]
[[ 1 -1  1 -1]]
Entropy:  [[24]]
